### ISSUE TITLE
Is there support for .NET Core 3.1?

### ISSUE THREAD

**Issue by hangjit-domain** [AppMetrics/AppMetrics#521]
We're using AppMetrics v1.3 and in the process of upgrading our app to .NET Core 3.1

The latest nuget v3.2 doesn't seem to have this extension `services.AddMetrics();`

Also we're now using Endpoint Routing instead of MVC Routing as per suggestions from .NET Core team.

What's the likely ETA for .NET Core 3.1 upgrade to be released if it's already not supported?

**Comment by vraravam** [comment]
I'm also starting a new project with .NetCore and would like to start with v3.1 - any ETA on when AppMetrics will support 3.1?

**Comment by ThomasSiigNoergaard** [comment]
Are you sure this isn't working? 
I have a 3.1 solution where the following works fine:

`          var metrics = new MetricsBuilder()
            .Report.ToConsole(TimeSpan.FromSeconds(10))
            .Build();

          services.AddMetrics(metrics);`

**Comment by hrai-domain** [comment]
> 
> 
> Are you sure this isn't working?
> I have a 3.1 solution where the following works fine:
> 
> ```
> var metrics = new MetricsBuilder()
>  .Report.ToConsole(TimeSpan.FromSeconds(10))
> .Build();
> 
> services.AddMetrics(metrics);
> ```

We've moved away from AppMetrics so I won't be able to test this code but it seems like others are having this issue. Otherwise, I'm happy for it to be closed.

**Comment by hrai-domain** [comment]
Elastic APM

**Comment by ThomasSiigNoergaard** [comment]
> I also having issues. I started a new .net 3.1 project just to try and get appMetrics working
> and it didn't work:
> 
> added to the HostBuilder
> 
> ```
>        public static IHostBuilder CreateHostBuilder(string[] args) =>
>             Host.CreateDefaultBuilder(args)
>                 .ConfigureWebHostDefaults(webBuilder =>
>                 {
>                     webBuilder.UseStartup<Startup>();
>                     webBuilder.UseMetrics();
>                 });
> ```
> 
> Added to Startup:Configure Services
> 
> ```
> services.AddMvc(option => option.EnableEndpointRouting = false); //disable endpoint routing
> services.AddMvcCore().AddMetricsCore();
> ```
> 
> with and without the following code
> 
> ```
>             var metrics = new MetricsBuilder()
>                  .Report.ToConsole(TimeSpan.FromSeconds(10))
>                 .Build();
>             services.AddMetrics(metrics);
> ```
> 
> changed Startup:Configure
> 
> ```
>             app.UseMvc();
>             //app.UseEndpoints(endpoints =>
>             //{
>             //    endpoints.MapRazorPages();
>             //});
> ```
> 
> Any ideas?

But you do have the extensions available, or is there a compileerror? The initial issue was that the extensions wasn't there...

**Comment by ThomasSiigNoergaard** [comment]
> what did you use instead?

And for the record, we've also moved away from AppMetrics. We're hosting on aws, and use their CloudWatch Metrics instead.

**Comment by serjebulavsky** [comment]
Any update regarding this ?

**Comment by seekingtheoptimal** [comment]
Can confirm that it is not working on 3.1 at all, and couldn't figure it out yet what exactly is the issue.

**Comment by timstokman** [comment]
App.Metrics.AspNetCore.Mvc references razor 2.2 through Microsoft.AspNetCore.Mvc , with asp core 3.1 it causes this issue: https://github.com/dotnet/sdk/issues/9932

Things might be solved by releasing a version with the dependencies upgraded.

**Comment by martinothamar** [comment]
Currently using this in a 3.1 stack, version I use is this: `4.0.0-preview1.0.3`

```
<PackageReference Include="App.Metrics" Version="$(AppMetricsVersion)" />
<PackageReference Include="App.Metrics.Formatters.Prometheus" Version="$(AppMetricsVersion)" />
<PackageReference Include="App.Metrics.AspNetCore" Version="$(AppMetricsVersion)" />
```

Don't know if previous versions don't work.

There's also the issue of making Kestrel work with the ASP.NET Core bits for some of the formatters (atleast Prometheus) as it currently tries to synchronously write to the response stream, so this is needed in the `ConfigureKestrel` call:
```
.ConfigureKestrel((context, options) =>
{
    options.AllowSynchronousIO = true;
})
```

There are open PR's to address this: #529 #533

Think the solution here is to maybe merge this: #534
And in any case try to finalize the 4.0.0 branch.

**Comment by daniel-white** [comment]
@martinothamar is there any progress on finalizing 4.0?

**Comment by martinothamar** [comment]
Im not sure, @alhardy is the maintainer so he would know if theres more work needed. Im using the latest preview - ASP.NET Core bits and the Prometheus formatter and its working great for my purposes. Synchronous IO thing has been fixed there in the latest preview

**Comment by alhardy** [comment]
@daniel-white yeah, I'll be pushing out a stable release soon

**Comment by iPilot** [comment]
Still in progress? For now `App.Metrics.AspNetCore.Mvc` doesn't have multitarget for 4.0.0 release.

**Comment by vraravam** [comment]
@alhardy - was this issue closed in error? I still don't see any updates in the `README.md` that talks about support for .Net core 3.1?

**Comment by duaneking** [comment]
This issue still persists as of the latest version.

**Comment by vraravam** [comment]
I too don't see support for .net 3.1 - please reopen.
